export const routes = {
  welcome: '/',
  dashboard: '/dashboard',
  login: '/login',
  register: '/register',
  test: '/test',
  work: '/work',
  personal: '/personal',
  fitness: '/fitness',
  otherTask: '/otherTask',
  statistic: '/statistic',
  editCalendar: '/editCalendar',
  allTasks: '/allTasks',
  settings: '/settings',
};
